"""
VisualMind database layer.

"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Generator

from dotenv import load_dotenv
from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import Session, declarative_base, relationship, sessionmaker


# Load environment variables from the project's .env file.
load_dotenv()

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "sqlite:///./data/products.db",
)

if DATABASE_URL.startswith("sqlite:///"):
    database_path = DATABASE_URL.removeprefix("sqlite:///")

    database_file = Path(database_path)

    # Resolve relative paths from the VisualMind project root.
    if not database_file.is_absolute():
        database_file = Path.cwd() / database_file

    # Create the parent directory if it doesn't already exist.
    database_file.parent.mkdir(parents=True, exist_ok=True)


connect_args = (
    {"check_same_thread": False}
    if DATABASE_URL.startswith("sqlite")
    else {}
)


engine = create_engine(
    DATABASE_URL,
    connect_args=connect_args,
    echo=False,
)


SessionLocal = sessionmaker(
    bind=engine,
    autocommit=False,
    autoflush=False,
)


Base = declarative_base()


class Product(Base):
    """
    Product metadata imported from the ABO dataset.

    Only the normalized fields needed by VisualMind are stored here.
    """

    __tablename__ = "products"

    # ABO's item_id becomes the stable primary key for a product.
    product_id = Column(
        String(64),
        primary_key=True,
    )

    # ABO product_type is normalized into the product category.
    category = Column(
        String(255),
        nullable=True,
        index=True,
    )

    # ABO color information is stored as the product's color.
    color = Column(
        String(255),
        nullable=True,
        index=True,
    )

    # Human-readable product name from ABO's item_name field.
    title = Column(
        Text,
        nullable=True,
    )

    # Combined searchable text built from ABO bullet points,
    # keywords, and style information.
    description = Column(
        Text,
        nullable=True,
    )

    # Relative path to the extracted local ABO image.
    image_path = Column(
        Text,
        nullable=True,
    )

    # Original ABO image identifier used to resolve the image path.
    main_image_id = Column(
        String(64),
        nullable=True,
        index=True,
    )

    # A product can have multiple automatically generated tags.
    tags = relationship(
        "Tag",
        back_populates="product",
        cascade="all, delete-orphan",
    )

    # A product can have multiple precomputed recommendations.
    recommendations = relationship(
        "Recommendation",
        foreign_keys="Recommendation.product_id",
        back_populates="product",
        cascade="all, delete-orphan",
    )


class Tag(Base):
    """
    Automatically generated product tag.

    Each tag is stored as an individual row so it can be queried and
    analyzed efficiently later.
    """

    __tablename__ = "tags"

    # Auto-incrementing identifier for the tag.
    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Product to which this tag belongs.
    product_id = Column(
        String(64),
        ForeignKey("products.product_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Tag group, such as category, color, or style.
    tag_type = Column(
        String(50),
        nullable=False,
        index=True,
    )

    # Actual tag value, such as "modern" or "blue".
    tag_value = Column(
        String(100),
        nullable=False,
        index=True,
    )

    # Connect the tag to its parent product.
    product = relationship(
        "Product",
        back_populates="tags",
    )


class SearchEvent(Base):
    """
    Search telemetry generated by every VisualMind search request.

    The same logical event will later be published to Kafka for NexusFlow.
    """

    __tablename__ = "search_events"

    # Auto-incrementing identifier for each search event.
    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Search modality: image, text, or multimodal.
    query_type = Column(
        String(30),
        nullable=False,
        index=True,
    )

    # User's textual query when one exists.
    query_text = Column(
        Text,
        nullable=True,
    )

    # Number of products returned by the search.
    result_count = Column(
        Integer,
        nullable=False,
    )

    # Highest-ranked product ID when the search returned results.
    top_result_id = Column(
        String(64),
        nullable=True,
        index=True,
    )

    # End-to-end search response time measured by the API.
    response_time_ms = Column(
        Float,
        nullable=False,
    )

    # UTC timestamp at which the search event was generated.
    timestamp = Column(
        DateTime,
        nullable=False,
        index=True,
    )


class Recommendation(Base):
    """
    Precomputed nearest-neighbor recommendation.

    These records are generated offline from the FAISS index so that
    product pages don't need to perform expensive searches repeatedly.
    """

    __tablename__ = "recommendations"

    # Auto-incrementing identifier for each recommendation.
    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # Product for which recommendations are being generated.
    product_id = Column(
        String(64),
        ForeignKey("products.product_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Product returned as a nearest-neighbor recommendation.
    recommended_product_id = Column(
        String(64),
        ForeignKey("products.product_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Cosine similarity returned by FAISS.
    similarity_score = Column(
        Float,
        nullable=False,
    )

    # Position of this recommendation in the ranked list.
    rank = Column(
        Integer,
        nullable=False,
    )

    # Link this recommendation to the source product.
    product = relationship(
        "Product",
        foreign_keys=[product_id],
        back_populates="recommendations",
    )


def init_db() -> None:
    """
    Create all VisualMind tables if they don't already exist.
    """

    # SQLAlchemy creates every table registered through the ORM models.
    Base.metadata.create_all(bind=engine)


def get_db() -> Generator[Session, None, None]:
    """
    Provide a database session and guarantee that it is closed afterward.

    FastAPI will later use this function as a dependency for API routes.
    """

    # Create a new database session for the current operation.
    db = SessionLocal()

    try:
        # Give the caller access to the database session.
        yield db
    finally:
        # Always close the session after the operation completes.
        db.close()

def get_products_by_ids(
    db: Session,
    product_ids: list[str],
) -> dict[str, Product]:
    """
    Retrieve products by their IDs and return them indexed by product ID.

    FAISS returns product positions, which are converted to product IDs
    before reaching this function.
    """

    # Avoid an unnecessary database query when FAISS returns no results.
    if not product_ids:
        return {}

    # Fetch all requested products in a single SQL query instead of
    # performing one query per search result.
    products = (
        db.query(Product)
        .filter(Product.product_id.in_(product_ids))
        .all()
    )

    # Build a dictionary for O(1) product lookup while preserving the
    # ordering returned by FAISS in the search route.
    return {
        product.product_id: product
        for product in products
    }