"""
VisualMind search endpoints.

This module contains image, text, and multimodal product-search
endpoints. All endpoints reuse the CLIP encoder and FAISS index
loaded once during FastAPI startup.

Every search is recorded in SQLite and published to Kafka for
downstream analytics.
"""

from __future__ import annotations

import io
import time
from datetime import datetime, timezone

import numpy as np
from fastapi import (
    APIRouter,
    Depends,
    File,
    Form,
    HTTPException,
    Request,
    UploadFile,
)
from PIL import Image, UnidentifiedImageError
from sqlalchemy.orm import Session

from api.core.fusion import (
    IMAGE_ALPHA,
    TEXT_ALPHA,
    fuse_embeddings,
)
from api.core.kafka_producer import kafka_producer
from api.database.database import (
    SearchEvent,
    get_db,
    get_products_by_ids,
)


# Group all search endpoints under /search.
router = APIRouter(
    prefix="/search",
    tags=["Search"],
)


def build_search_results(
    request: Request,
    db: Session,
    query_vector: np.ndarray,
    top_k: int = 10,
) -> list[dict]:
    """
    Search FAISS using a normalized CLIP vector and resolve the
    resulting product IDs against SQLite.
    """

    # Retrieve the FAISS index loaded once during application startup.
    index = request.app.state.faiss_index

    # Retrieve the FAISS-position → product-ID mapping loaded at startup.
    metadata = request.app.state.embeddings_metadata

    # FAISS expects a two-dimensional float32 matrix.
    query_matrix = np.ascontiguousarray(
        query_vector.reshape(1, -1),
        dtype=np.float32,
    )

    # Never request more vectors than actually exist in the index.
    search_k = min(top_k, index.ntotal)

    # Search using inner product, which equals cosine similarity because
    # both stored and query vectors are L2-normalized.
    similarities, positions = index.search(
        query_matrix,
        search_k,
    )

    # Convert FAISS positions into stable product IDs.
    product_ids = metadata["product_ids"]

    ranked_ids = [
        product_ids[position]
        for position in positions[0]
        if position >= 0
    ]

    # Resolve all product metadata with one database query.
    products_by_id = get_products_by_ids(
        db,
        ranked_ids,
    )

    results: list[dict] = []

    # Preserve the exact ranking generated by FAISS.
    for rank, (position, similarity) in enumerate(
        zip(positions[0], similarities[0]),
        start=1,
    ):
        # FAISS uses -1 when no result exists for a requested position.
        if position < 0:
            continue

        # Convert the FAISS vector position to the corresponding product.
        product_id = product_ids[position]

        # Ignore stale FAISS entries if the product was removed from SQLite.
        product = products_by_id.get(product_id)

        if product is None:
            continue

        results.append(
            {
                "rank": rank,
                "product_id": product.product_id,
                "title": product.title,
                "category": product.category,
                "color": product.color,
                "image_path": product.image_path,
                "similarity": float(similarity),
            }
        )

    return results


def decode_uploaded_image(
    image_bytes: bytes,
) -> Image.Image:
    """
    Decode uploaded bytes into an RGB PIL image.
    """

    # Reject empty uploads before attempting image decoding.
    if not image_bytes:
        raise HTTPException(
            status_code=400,
            detail="Uploaded image is empty.",
        )

    try:
        # Decode the uploaded bytes as an image.
        image = Image.open(
            io.BytesIO(image_bytes)
        )

        # Force complete decoding so corrupted files are detected now.
        image.load()

        # CLIP expects RGB images.
        return image.convert("RGB")

    except (UnidentifiedImageError, OSError) as exc:
        # Convert PIL errors into a clean API response.
        raise HTTPException(
            status_code=400,
            detail="Invalid image file.",
        ) from exc


def record_search_event(
    *,
    db: Session,
    query_type: str,
    query_text: str | None,
    results: list[dict],
    response_time_ms: float,
) -> None:
    """
    Record a search event in SQLite and publish it to Kafka.

    Analytics failures never cause the actual search request to fail.
    """

    # The first result is the highest-ranked FAISS result.
    top_result_id = (
        results[0]["product_id"]
        if results
        else None
    )

    result_count = len(results)

    # Use UTC for consistent analytics timestamps.
    timestamp = datetime.now(timezone.utc).replace(
        tzinfo=None
    )

    # ----------------------------------------------------------
    # SQLite
    # ----------------------------------------------------------

    database_event = SearchEvent(
        query_type=query_type,
        query_text=query_text,
        result_count=result_count,
        top_result_id=top_result_id,
        response_time_ms=response_time_ms,
        timestamp=timestamp,
    )

    try:
        # Persist the search event locally.
        db.add(database_event)
        db.commit()

    except Exception as exc:
        # Roll back so the SQLAlchemy session remains usable.
        db.rollback()

        # Analytics must never break a successful search.
        print(
            "SQLite search event could not be recorded: "
            f"{exc}"
        )

    # ----------------------------------------------------------
    # Kafka
    # ----------------------------------------------------------

    # Publish the same event to Kafka for NexusFlow/analytics.
    kafka_producer.publish_search_event(
        query_type=query_type,
        query_text=query_text,
        result_count=result_count,
        top_result_id=top_result_id,
        response_time_ms=response_time_ms,
    )


@router.post("/image")
async def search_by_image(
    request: Request,
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
):
    """
    Search products using an uploaded product image.
    """

    # Start measuring the complete search operation.
    start_time = time.perf_counter()

    # Validate the MIME type before processing the upload.
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(
            status_code=400,
            detail="Uploaded file must be an image.",
        )

    # Read the uploaded image into memory.
    image_bytes = await file.read()

    # Convert the uploaded bytes into an RGB PIL image.
    image = decode_uploaded_image(image_bytes)

    # Reuse the single CLIP model loaded during FastAPI startup.
    encoder = request.app.state.clip_encoder

    # Generate the normalized 512-dimensional image embedding.
    query_vector = encoder.encode_image(image)

    # Search the shared FAISS index.
    results = build_search_results(
        request=request,
        db=db,
        query_vector=query_vector,
    )

    # Calculate total search time.
    response_time_ms = (
        time.perf_counter() - start_time
    ) * 1000

    # Record the search in SQLite and Kafka.
    record_search_event(
        db=db,
        query_type="image",
        query_text=None,
        results=results,
        response_time_ms=response_time_ms,
    )

    return {
        "query_type": "image",
        "result_count": len(results),
        "results": results,
    }


@router.post("/text")
async def search_by_text(
    request: Request,
    query: str = Form(...),
    db: Session = Depends(get_db),
):
    """
    Search products using a natural-language text query.
    """

    # Start measuring the complete search operation.
    start_time = time.perf_counter()

    # Remove accidental whitespace around the user's query.
    query = query.strip()

    # Reject empty search queries.
    if not query:
        raise HTTPException(
            status_code=400,
            detail="Search query cannot be empty.",
        )

    # Reuse the single CLIP model loaded during FastAPI startup.
    encoder = request.app.state.clip_encoder

    # Generate the normalized 512-dimensional text embedding.
    query_vector = encoder.encode_text(query)

    # Search the shared FAISS index.
    results = build_search_results(
        request=request,
        db=db,
        query_vector=query_vector,
    )

    # Calculate total search time.
    response_time_ms = (
        time.perf_counter() - start_time
    ) * 1000

    # Record the search in SQLite and Kafka.
    record_search_event(
        db=db,
        query_type="text",
        query_text=query,
        results=results,
        response_time_ms=response_time_ms,
    )

    return {
        "query_type": "text",
        "query": query,
        "result_count": len(results),
        "results": results,
    }


@router.post("/multimodal")
async def search_multimodal(
    request: Request,
    file: UploadFile = File(...),
    query: str = Form(...),
    db: Session = Depends(get_db),
):
    """
    Search products using both an image and a text refinement.
    """

    # Start measuring the complete search operation.
    start_time = time.perf_counter()

    # Validate the uploaded file before reading it.
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(
            status_code=400,
            detail="Uploaded file must be an image.",
        )

    # Remove whitespace from the textual refinement.
    query = query.strip()

    # A multimodal search requires an actual textual refinement.
    if not query:
        raise HTTPException(
            status_code=400,
            detail="Search query cannot be empty.",
        )

    # Read the uploaded image.
    image_bytes = await file.read()

    # Decode and normalize the image into RGB.
    image = decode_uploaded_image(image_bytes)

    # Reuse the single CLIP model loaded during FastAPI startup.
    encoder = request.app.state.clip_encoder

    # Encode the image and text independently.
    image_embedding = encoder.encode_image(image)
    text_embedding = encoder.encode_text(query)

    # Combine both normalized CLIP representations using the configured
    # image/text weighting and normalize the resulting vector again.
    fused_embedding = fuse_embeddings(
        image_embedding=image_embedding,
        text_embedding=text_embedding,
    )

    # Search the fused representation against the same FAISS index.
    results = build_search_results(
        request=request,
        db=db,
        query_vector=fused_embedding,
    )

    # Calculate total search time.
    response_time_ms = (
        time.perf_counter() - start_time
    ) * 1000

    # Record the search in SQLite and Kafka.
    record_search_event(
        db=db,
        query_type="multimodal",
        query_text=query,
        results=results,
        response_time_ms=response_time_ms,
    )

    return {
        "query_type": "multimodal",
        "query": query,
        "image_weight": IMAGE_ALPHA,
        "text_weight": TEXT_ALPHA,
        "result_count": len(results),
        "results": results,
    }
