"""
VisualMind FastAPI application.
"""

from contextlib import asynccontextmanager
from pathlib import Path
import pickle

import faiss
from fastapi import FastAPI

from api.core.clip_encoder import CLIPEncoder
from api.routes.search import router as search_router
from api.routes.recommendations import router as recommendations_router
# Resolve the project root from this file:
# visualmind/api/main.py -> visualmind/
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Persistent FAISS index generated by pipeline/index_builder.py.
FAISS_INDEX_PATH = PROJECT_ROOT / "data" / "faiss_index.bin"

# Mapping between FAISS vector positions and product IDs.
METADATA_PATH = PROJECT_ROOT / "data" / "embeddings_metadata.pkl"


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Load VisualMind's ML resources once when FastAPI starts.

    The resources are stored in app.state so every endpoint can reuse
    the same CLIP model and FAISS index without reloading them.
    """

    print("=" * 60)
    print("Starting VisualMind API")
    print("=" * 60)

    # Load CLIP exactly once for the lifetime of the API process.
    app.state.clip_encoder = CLIPEncoder()

    print("Loading FAISS index...")

    # Load the already-built vector index from disk instead of rebuilding it.
    app.state.faiss_index = faiss.read_index(
        str(FAISS_INDEX_PATH)
    )

    print(
        f"FAISS index loaded: "
        f"{app.state.faiss_index.ntotal:,} vectors"
    )

    # Load the mapping that converts FAISS positions into product IDs.
    with METADATA_PATH.open("rb") as file:
        app.state.embeddings_metadata = pickle.load(file)

    # Validate that the mapping and FAISS index contain the same number
    # of vectors before allowing the API to start.
    product_ids = app.state.embeddings_metadata["product_ids"]

    if len(product_ids) != app.state.faiss_index.ntotal:
        raise RuntimeError(
            "FAISS index and product mapping have different sizes: "
            f"{app.state.faiss_index.ntotal} vs {len(product_ids)}"
        )

    print(
        f"Product mapping loaded: "
        f"{len(product_ids):,} entries"
    )

    print("=" * 60)
    print("VisualMind API ready")
    print("=" * 60)

    # Everything above remains available while FastAPI is running.
    yield

    # Release the references when the application shuts down.
    app.state.clip_encoder = None
    app.state.faiss_index = None
    app.state.embeddings_metadata = None

    print("VisualMind API shut down.")


# Create the FastAPI application and attach the startup/shutdown lifecycle.
app = FastAPI(
    title="VisualMind API",
    description="Multimodal product search API",
    version="0.1.0",
    lifespan=lifespan,
)

app.include_router(search_router)
app.include_router(recommendations_router)
@app.get("/health")
async def health() -> dict:
    """
    Basic health endpoint used to verify that the API is running.
    """

    # Check whether the startup lifecycle successfully loaded the
    # required ML resources.
    clip_loaded = (
        getattr(app.state, "clip_encoder", None) is not None
    )

    faiss_index = getattr(
        app.state,
        "faiss_index",
        None,
    )

    return {
        "status": "healthy",
        "clip_loaded": clip_loaded,
        "faiss_loaded": faiss_index is not None,
        "faiss_vectors": (
            faiss_index.ntotal
            if faiss_index is not None
            else 0
        ),
    }